trigger: none
# trigger:
#     - azure-pipelines

pool:
    vmImage: ubuntu-latest

variables:
    CI: true

stages:
    - stage: "Preparetion_and_test"
      displayName: "Preparetion"
      jobs:
          - job: "Compile_Test_Code_Analysis"
            displayName: "Preparetion and test"
            
            # Our angular project uses Node.js v14.21.3
            steps:
                - task: NodeTool@0
                  inputs:
                      versionSource: "spec"
                      versionSpec: "14.x"
                  displayName: "Install Node.js"
                - task: Npm@1
                  inputs:
                      command: "install"
                  displayName: "Install dependencies"
                
                #  Build and compile the Angular project
                - task: Npm@1
                  inputs:
                      command: "custom"
                      customCommand: "run build"
                  displayName: "Run build for compiling"
                
                # Run unit tests and test coverage
                - script: |
                      npx ng test --code-coverage --watch=false
                  displayName: "Run unit tesing and access the code coverage"

                # Accessing the code coverage
                - task: PublishCodeCoverageResults@1
                  displayName: "Access and Publish code coverage results"
                  condition: succeededOrFailed()
                  inputs:
                      codeCoverageTool: "Cobertura"
                      summaryFileLocation: "coverage/angular11-testing-examples/cobertura-coverage.xml"
                      reportDirectory: "coverage/angular11-testing-examples/"
                      failIfCoverageEmpty: false
                    
                # Accessing the unit testing results report
                - task: PublishTestResults@2
                  displayName: "Access and Publish unit test results"
                  condition: succeededOrFailed()
                  inputs:
                      searchFolder: $(System.DefaultWorkingDirectory)
                      testRunTitle: Angular
                      testResultsFormat: JUnit
                      testResultsFiles: "src/test-results/Chrome_Headless_117.0.5938.132_(Linux_x86_64)/TESTS-results.xml"

                # Linting and code analysis
                - task: Npm@1
                  inputs:
                      command: "custom"
                      customCommand: "run lint"
                  displayName: "Run Linting and code quality analysis"
