trigger:
    - azure-pipelines
variables:
    CI: true

pool:
    vmImage: ubuntu-latest

stages:
    - stage: "Preparetion_and_test"
      displayName: "Preparetion"
      jobs:
          - job: "Compile_Test_Code_Analysis"
            displayName: "Preparetion and test"
            steps:
                - task: NodeTool@0
                  inputs:
                      versionSource: "spec"
                      versionSpec: "14.x"
                  displayName: "Install Node.js"
                - task: Npm@1
                  inputs:
                      command: "install"
                  displayName: "Install dependencies"
                - task: Npm@1
                  inputs:
                      command: "custom"
                      customCommand: "run build"
                  displayName: "Run build for compiling"
                
                - script: pwd && ls -al
                  displayName: "List contents before tests"

                - script: |
                      npx ng test --code-coverage --watch=false --single-run
                  displayName: "Run unit tesing and access the code coverage"

                - script: ls -al coverage/
                  displayName: "List contents of coverage directory"


                - task: PublishCodeCoverageResults@1
                  displayName: "Publish code coverage Angular results"
                  condition: succeededOrFailed()
                  inputs:
                      codeCoverageTool: "Cobertura"
                      summaryFileLocation: "coverage/angular11-testing-examples/cobertura-coverage.xml"
                      reportDirectory: "coverage/angular11-testing-examples/"
                      failIfCoverageEmpty: false

                - task: PublishTestResults@2
                  displayName: "Publish Angular test results"
                  condition: succeededOrFailed()
                  inputs:
                      searchFolder: $(System.DefaultWorkingDirectory)
                      testRunTitle: Angular
                      testResultsFormat: JUnit
                      testResultsFiles: "**/test-results/TESTS-*.xml"

                - task: Npm@1
                  inputs:
                      command: "custom"
                      customCommand: "run lint"
                  displayName: "Run Linting and code quality analysis"
