parameters:
    - name: vmImage
      type: string
      default: "ubuntu-latest"
    - name: repository
      type: string
      default: ""
    - name: dockerfile
      type: string
      default: ""
    - name: containerRegistry
      type: string
      default: ""
    - name: tag
      type: string
      default: ""

stages:
    - stage: Build
      displayName: Build and push stage
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      dependsOn: SAST
      jobs:
          - job: Build
            displayName: Build
            pool:
                vmImage: ${{parameters.vmImage}}
            steps:
                - task: Docker@2
                  displayName: Build and push an image to container registry
                  inputs:
                      command: buildAndPush
                      repository: ${{parameters.repository}}
                      dockerfile: ${{parameters.dockerfile}}
                      containerRegistry: ${{parameters.containerRegistry}}
                      tags: |
                          ${{parameters.tag}}

                - task: PublishPipelineArtifact@1
                  displayName: Publish the manifests folder to pipeline
                  inputs:
                      targetPath: "$(Build.SourcesDirectory)/manifests"
                      artifact: "manifests"
                      publishLocation: "pipeline"
